### PR TITLE
Reconnection and keyboard longpress

### PR DESCRIPTION
**Pull request by YunxiangChi**

### CODE REVIEW

**Comment by Binghong-Leo-Li** [comment]
[Drool]

**Comment by Binghong-Leo-Li** [comment]
😍

**Comment by YunxiangChi** [comment]
😘

**Comment by Binghong-Leo-Li** [comment]
lgtm but prob gonna wait for Xiyan, as we pretty much wrote the code together @YunxiangChi

**Comment by xiyan128** [comment]
looking at the pr rn

**Review by xiyan128 — APPROVED** [review]
made some changes locally

**Pull request merged**
