### PR TITLE
Added weather system (physics + particle effects + UI icon)

### PR DESCRIPTION
**Pull request by xiyan128**
To be fixed: rain particle direction
To be added: wind particles

the command handlers are split into files, so it might be better if we merge sooner to avoid large diffs later

### CODE REVIEW

**Review by YunxiangChi — COMMENTED** [review]
did you push rain_particle.png though? It seems like I couldn't find that:
error finding particles/rain_particle.png', /Users/YunxiangChi/Documents/code/Rust/CSE125/group-5/client/src/lib.rs:528:14

**Review by YunxiangChi — COMMENTED** [review]
And btw I can help with handling conflicts though

**Comment by YunxiangChi** [comment]
> And btw I can help with handling conflicts though

I just finished rebase at another branch "weather_aim_for_rebase" since I'm afriad some issues during rebase gonna cause some unexpected bugs that's hard to find.
And you can test it there.

**Comment by xiyan128** [comment]
> > And btw I can help with handling conflicts though
> 
> I just finished rebase at another branch "weather_aim_for_rebase" since I'm afriad some issues during rebase gonna cause some unexpected bugs that's hard to find. And you can test it there.

I'll check it out, many thanks. Also pushed the missing rain particle texture.

**Pull request closed without merging**
