### PR TITLE
change lightning to blizzard powerup

### PR DESCRIPTION
**Pull request by alanlwang1**
TODO: get new UI icon for blizzard

### CODE REVIEW

**Comment by xiyan128** [comment]
TODO2: color of particles

**Review by xiyan128 — APPROVED** [review]
maybe someone else can take another look

(i added commits to this pr

**Comment by alanlwang1** [comment]
changed color of particles, someone else can take a look now

**Comment by shuhua-xie** [comment]
Looks good to me, just needs a new icon

**Pull request merged**
