### PR TITLE
Update in-game 2DUI

### PR DESCRIPTION
**Pull request by YunxiangChi**

### CODE REVIEW

**Comment by xiyan128** [comment]
do we have higher resolution assets?

**Comment by Binghong-Leo-Li** [comment]
True, the resolution is a bit low...

**Comment by Binghong-Leo-Li** [comment]
Also did we want colors for the powerups as well? For the 2D UI?

**Comment by Binghong-Leo-Li** [comment]
BTW, would it be an issue that the powerup icon is emptied while there's still like a second or so on the status effect? I believe that is because the percentage filling is calculated based on the entire png rather than just the circular area? As of now, the indication is a little not-aligned (that when I see the powerup is fully empty, there's still some time remaining).

**Comment by shuhua-xie** [comment]
Ok, I've updated the images
- the low quality text and scaled down icons is probably a sampling issue. we only sample 1 texel and don't do any sort of mipmapping, so the quality is so-so
- we still need to add the second cooldown for skills that have one

**Comment by shuhua-xie** [comment]
should be good to merge now, we can add the second cooldown later?

**Review by Binghong-Leo-Li — APPROVED** [review]
Think it's good now

**Comment by Binghong-Leo-Li** [comment]
LGTM, Good work

**Pull request merged**
